# Generated by Django 6.0.1 on 2026-02-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnos',
            options={'ordering': ['-created'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
    ]
